name: Linting

on: push

jobs:
  lint:
    name: Check Code Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run ESLint
        run: pnpm lint